/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dekiemtra;

/**
 *
 * @author C
 */
public class DScongviec extends javax.swing.JFrame {

    /**
     * Creates new form DScongviec
     */
    public DScongviec() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnok = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        rdopt1 = new javax.swing.JRadioButton();
        rdopt2 = new javax.swing.JRadioButton();
        rdosnt = new javax.swing.JRadioButton();
        rdofbn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sách công việc");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Lựa chọn công việc");

        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });

        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdopt1);
        rdopt1.setText("Giải phương trình bậc nhất");

        buttonGroup1.add(rdopt2);
        rdopt2.setText("Giải phương trình bậc 2");
        rdopt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdopt2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdosnt);
        rdosnt.setText("Kiểm tra số nguyên tố");
        rdosnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdosntActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdofbn);
        rdofbn.setText("Số Fibonacci");
        rdofbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdofbnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnexit))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(rdopt2)
                        .addComponent(rdofbn, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rdosnt, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1)
                    .addComponent(rdopt1))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(rdopt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdopt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdosnt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdofbn)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnok)
                    .addComponent(btnexit))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdofbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdofbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdofbnActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_btnexitActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        if (rdosnt.isSelected()) {
            SoNguyenTo snt = new SoNguyenTo();
            snt.setVisible(true);
            this.hide();
        }
        if (rdopt1.isSelected()) {
            PhuongTrinhBac1 pt1 = new PhuongTrinhBac1();
            pt1.setVisible(true);
            this.hide();
        }
        if (rdopt2.isSelected()) {
            PhuongTrinhBac2 pt2 = new PhuongTrinhBac2();
            pt2.setVisible(true);
            this.hide();
        }
        if (rdofbn.isSelected()) {
            SoFibonacci fbn = new SoFibonacci();
            fbn.setVisible(true);
            this.hide();
        }
    }//GEN-LAST:event_btnokActionPerformed

    private void rdosntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdosntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdosntActionPerformed

    private void rdopt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdopt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdopt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DScongviec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DScongviec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DScongviec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DScongviec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DScongviec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnok;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rdofbn;
    private javax.swing.JRadioButton rdopt1;
    private javax.swing.JRadioButton rdopt2;
    private javax.swing.JRadioButton rdosnt;
    // End of variables declaration//GEN-END:variables
}
